name: environment-cpu
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - torch -f https://download.pytorch.org/whl/cpu
      - torchvision -f https://download.pytorch.org/whl/cpu
      - torchaudio -f https://download.pytorch.org/whl/cpu 
      - transformers
      - peft
      - jupyter
      - numpy==1.26.4
      - pandas
      - scikit-learn
      - matplotlib
      - tqdm
      - openpyxl